import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const links='/root/.cache/ms-playwright/.links';
const candidates=fs.readdirSync(links).map(f=>fs.readFileSync(path.join(links,f),'utf8')).filter(p=>fs.existsSync(p+'/package.json'));
const {chromium}=require(process.env.PLAYWRIGHT_CORE || candidates[0]);
const executablePath=process.env.CHROMIUM || '/root/.cache/ms-playwright/chromium_headless_shell-1234/chrome-linux/headless_shell';
const out=path.resolve(process.env.EVIDENCE || 'evidence/candidate-browser-01');fs.mkdirSync(out,{recursive:true});
const browser=await chromium.launch({executablePath,headless:true,args:['--no-sandbox']});
const base=process.env.BASE_URL || 'http://127.0.0.1:48493';
try {
 const page=await browser.newPage({viewport:{width:1440,height:1050},acceptDownloads:true});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base);
 await page.locator('#generate').click();
 await page.waitForFunction(()=>window.workbench?.revision);
 const initial=await page.evaluate(()=>structuredClone(window.workbench));
 assert.equal(await page.locator('#confirmGeneration').count(),1,'actual quote/confirmation UI missing');
 assert(await page.locator('#confirmGeneration').isDisabled());
 const fixture=path.join(out,'TECHNICAL-FIXTURE-NOT-ART.png');
 fs.writeFileSync(fixture,await (await page.request.get(base+`/api/layouts/${initial.revision}/artifacts/clean-guide.png`)).body());
 await page.locator('#styleFile').setInputFiles(fixture);
 await page.locator('#uploadStyle').click();
 await page.waitForFunction(()=>window.styleReference?.id);
 assert.equal(await page.evaluate(()=>window.styleReference.role),'style_only');
 await page.locator('#terrainFile').setInputFiles(fixture);
 await page.locator('#importTerrain').click();
 await page.waitForFunction(()=>window.candidate?.id);
 assert.equal(await page.evaluate(()=>window.candidate.production_approved),false);
 await page.locator('#view').selectOption('candidate');
 await page.waitForFunction(()=>window.candidateImage?.complete);
 await page.locator('#scene').focus();await page.keyboard.press('ArrowRight');
 assert.notDeepEqual(await page.evaluate(()=>window.workbench.actor),initial.actor);
 await page.screenshot({path:path.join(out,'candidate-playable-TECHNICAL-FIXTURE.png'),fullPage:true});
 await page.locator('#stage').screenshot({path:path.join(out,'playable-detail-TECHNICAL-FIXTURE.png')});
 await page.locator('#view').selectOption('comparison');
 assert(await page.locator('#stage').isHidden(),'comparison must not leave an empty stage above diagnostics');
 await page.screenshot({path:path.join(out,'candidate-guide-diagnostics-TECHNICAL-FIXTURE.png'),fullPage:true});
 await page.locator('#comparison').screenshot({path:path.join(out,'comparison-detail-TECHNICAL-FIXTURE.png')});
 await page.locator('#finalDensity').selectOption('2');
 const dl=page.waitForEvent('download');await page.locator('#candidateDownload').click();
 const download=await dl;await download.saveAs(path.join(out,download.suggestedFilename()));
 assert.equal(await download.failure(),null);
 // FREE live metadata only. No external media upload, confirmation or paid generation.
 await page.locator('#quoteGeneration').click();
 await page.waitForFunction(()=>document.querySelector('#generationReport').textContent.includes('USD') || document.querySelector('#generationReport').textContent.includes('unavailable'),null,{timeout:60000});
 const quote=await page.locator('#generationReport').innerText();
 assert(await page.locator('#confirmGeneration').isDisabled());
 await page.screenshot({path:path.join(out,'free-quote-budget-blocked.png'),fullPage:true});
 await page.locator('#brief').fill('Platz; Weg Kreuz; 4 Bäume');await page.locator('#seed').fill('81');
 await page.locator('#generate').click();await page.waitForFunction(r=>window.workbench.revision!==r,initial.revision);
 assert.equal(await page.locator('#example').inputValue(),'custom');
 assert.equal(await page.evaluate(()=>window.candidate),null);
 assert(await page.locator('#candidateDownload').isHidden());
 await page.setViewportSize({width:390,height:844});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.screenshot({path:path.join(out,'mobile-current-revision.png'),fullPage:true});
 await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:path.join(out,'mobile-controls.png')});
 assert.deepEqual(errors,[]);
 fs.writeFileSync(path.join(out,'candidate-browser-report.json'),JSON.stringify({fixture:'TECHNICAL GUIDE ONLY; NOT PRODUCTION ART',download:download.suggestedFilename(),revision:initial.revision,errors,quote},null,2));
 console.log(JSON.stringify({result:'PASS',out,download:download.suggestedFilename(),errors}));
} finally {await browser.close();}
