/* Retained genuine two-style results; never buys or starts a new batch. */
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),links='/root/.cache/ms-playwright/.links';const roots=fs.readdirSync(links).map(f=>fs.readFileSync(path.join(links,f),'utf8')).filter(p=>fs.existsSync(p+'/package.json'));const {chromium}=require(roots[0]);
const browser=await chromium.launch({executablePath:'/root/.cache/ms-playwright/chromium_headless_shell-1234/chrome-linux/headless_shell',headless:true,args:['--no-sandbox']});const base=process.env.BASE_URL||'http://127.0.0.1:59661',root='evidence/overnight-two-styles',out=process.env.EVIDENCE||root+'/browser';fs.mkdirSync(out,{recursive:true});
try{
 const page=await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const batch=JSON.parse(fs.readFileSync(root+'/batch-readback.json'));assert.equal(batch.status,'completed');const [warm,fantasy]=batch.styles;
 const before=await(await page.request.get(base+'/api/generation/status')).json();assert.equal(before.enabled,false);
 const closedConfirm=await page.request.post(base+'/api/generation/confirm',{data:{quote_id:warm.quote_id,revision:batch.frozen.revision,style_spec_id:warm.style_spec_id}});assert.equal(closedConfirm.status(),403);
 const closedReview=await page.request.post(base+'/api/evaluations/'+warm.evaluation_id+'/review',{data:{confirm_paid:true}});assert.equal(closedReview.status(),403);
 const retained=w=>{const {display_status,terminal,can_resume,can_cancel,...raw}=w;return {...raw,styles:raw.styles.map(({display_status,...a})=>a)};};
 const afterResume=await(await page.request.post(base+'/api/overnight-batch/'+batch.id+'/resume')).json();assert.equal(afterResume.display_status,'blocked');assert.deepEqual(retained(afterResume),batch);
 const duplicateResponse=await page.request.post(base+'/api/overnight-batch/start',{data:JSON.parse(fs.readFileSync(root+'/start-request.json'))});
 const currentRegistrationHash=createHash('sha256').update(fs.readFileSync('auto_adapter.py')).digest('hex');
 if(currentRegistrationHash===batch.frozen.registration_sha256){assert.equal(duplicateResponse.status(),201);assert.deepEqual(retained(await duplicateResponse.json()),batch);}
 else {assert.equal(duplicateResponse.status(),409,'changed frozen implementation must reject a fresh start');assert.deepEqual(retained(await(await page.request.get(base+'/api/overnight-batch/'+batch.id)).json()),batch);}
 for(const a of batch.styles){const poll=await(await page.request.post(base+'/api/generation/jobs/'+a.job_id+'/resume')).json();assert.equal(poll.candidate_id,a.source_candidate_id);assert.equal(poll.status,'candidate_ready');}
 await page.goto(base);await page.waitForFunction(()=>window.overnightBatch?.terminal===true);assert.equal(await page.locator('#savedBatches').inputValue(),batch.id);assert(await page.locator('#batchResume').isDisabled());assert(await page.locator('#batchCancel').isDisabled());assert.match(await page.locator('#batchProgress').innerText(),/succeeded/);assert.match(await page.locator('#batchProgress').innerText(),/blocked/);await page.locator('#batchPanel').screenshot({path:out+'/saved-batch-panel.png'});await page.reload();await page.waitForFunction(()=>window.overnightBatch?.terminal===true);assert.equal(await page.locator('#batchId').inputValue(),batch.id);await page.locator('#brief').fill('');await page.getByText('Explizite Formparameter (optional)',{exact:true}).click();
 for(const [id,value] of Object.entries({width:'14',height:'14',seed:'2026092101',trees:'0',houses:'0',actor_width:'0.8'}))await page.locator('#'+id).fill(value);
 await page.locator('#kind').selectOption('plaza');await page.locator('#path').selectOption('cross');await page.locator('#generate').click();await page.waitForFunction(()=>window.workbench?.revision);assert.equal(await page.evaluate(()=>window.workbench.revision),batch.frozen.revision);
 await page.locator('#diagnostics').uncheck();await page.locator('#zoom').click();await page.locator('#scene').screenshot({path:out+'/before-blockout-native.png'});
 let de=page.waitForEvent('download');await page.locator('#download').click();let dl=await de;await dl.saveAs(out+'/'+dl.suggestedFilename());const layoutDownload=dl.suggestedFilename();
 await page.locator('#candidateId').fill(warm.candidate_id);await page.locator('#loadCandidate').click();await page.waitForFunction(id=>window.candidateImage?.complete&&window.candidate?.id===id,warm.candidate_id);
 await page.locator('#styleSpecEditor').fill(fs.readFileSync(root+'/warm/style-spec-request.json','utf8'));await page.locator('#saveStyleSpec').click();await page.waitForFunction(id=>window.styleSpec?.id===id,warm.style_spec_id);
 await page.locator('#prepareEvaluation').click();await page.waitForFunction(()=>window.currentEvaluation?.status==='reviewed');assert.equal(await page.evaluate(()=>window.currentEvaluation.id),warm.evaluation_id);assert.equal(await page.evaluate(()=>window.currentEvaluation.gate.production_approved),true);
 assert(await page.locator('#paidReview').isDisabled());await page.locator('#strictReviewPanel').screenshot({path:out+'/warm-strict-gate.png'});
 const initial=await page.evaluate(()=>structuredClone(window.workbench)),graph=initial.validation.graph;
 const key=(a,b)=>b[0]>a[0]?'ArrowRight':b[0]<a[0]?'ArrowLeft':b[1]>a[1]?'ArrowDown':'ArrowUp';
 async function walk(goal){const start=await page.evaluate(()=>[...window.workbench.actor]);const parents=new Map([[start.join(','),null]]),queue=[start];for(let i=0;i<queue.length;i++)for(const b of graph[queue[i].join(',')]||[])if(!parents.has(b.join(','))){parents.set(b.join(','),queue[i]);queue.push(b);}assert(parents.has(goal.join(',')));const route=[];for(let at=goal;at!==null;at=parents.get(at.join(',')))route.push(at);route.reverse();await page.locator('#scene').focus();for(let i=1;i<route.length;i++)await page.keyboard.press(key(route[i-1],route[i]));assert.deepEqual(await page.evaluate(()=>window.workbench.actor),goal);return route.length-1;}
 await page.locator('#view').selectOption('candidate');const navigation=[];for(const goal of initial.layout.goals)navigation.push({goal,steps:await walk(goal)});
 await walk([0,0]);await page.keyboard.press('ArrowLeft');assert.deepEqual(await page.evaluate(()=>window.workbench.actor),[0,0]);assert.match(await page.locator('#motion').innerText(),/Blockiert/);navigation.push({kind:'world-boundary',blocked:true});await walk(initial.layout.spawn);
 await page.locator('#scene').evaluate(e=>e.blur());await page.locator('#scene').screenshot({path:out+'/warm-gameplay-native.png'});
 const sampling=await page.evaluate(()=>{const c=document.querySelector('#scene'),r=c.getBoundingClientRect();return {canvas:[c.width,c.height],css:[r.width,r.height],position:[r.x,r.y],dpr:devicePixelRatio,actor:window.workbench.actor,background:getComputedStyle(document.querySelector('#stage')).backgroundColor};});assert.deepEqual(sampling.canvas,sampling.css);assert(sampling.position.every(Number.isInteger));assert.equal(sampling.dpr,1);
 await page.locator('#stage').screenshot({path:out+'/warm-gameplay-stage.png'});await page.locator('#view').selectOption('comparison');await page.locator('#comparison').screenshot({path:out+'/warm-original-vs-guide.png'});
 de=page.waitForEvent('download');await page.locator('#candidateDownload').click();dl=await de;await dl.saveAs(out+'/'+dl.suggestedFilename());assert.equal(await dl.failure(),null);const diagnostic=dl.suggestedFilename();
 de=page.waitForEvent('download');await page.locator('#productionExport').click();dl=await de;await dl.saveAs(out+'/'+dl.suggestedFilename());assert.equal(await dl.failure(),null);const production=dl.suggestedFilename();
 const stale=await page.request.get(base+`/api/terrain/${warm.candidate_id}/download?revision=${batch.frozen.revision}&density=2&mode=production&style_spec_id=${warm.style_spec_id}&evaluation_id=${warm.evaluation_id}`);assert.equal(stale.status(),409);
 await page.locator('#candidateId').fill(fantasy.source_candidate_id);await page.locator('#loadCandidate').click();await page.waitForFunction(id=>window.candidate?.id===id,fantasy.source_candidate_id);assert.match(await page.locator('#candidateStatus').innerText(),/rejected/);assert.equal(await page.locator('#candidateDownload').isVisible(),false);await page.locator('#view').selectOption('comparison');await page.locator('#comparison').screenshot({path:out+'/fantasy-source-diagnostic-NOT-GAMEPLAY.png'});await page.locator('#candidateStatus').screenshot({path:out+'/fantasy-rejected.png'});
 const blocked=await page.request.get(base+`/api/terrain/${fantasy.source_candidate_id}/download?revision=${batch.frozen.revision}&density=1`);assert.equal(blocked.status(),422);const denied=await page.request.get(base+`/api/terrain/${fantasy.source_candidate_id}/download?revision=${batch.frozen.revision}&density=1&mode=production`);assert.equal(denied.status(),409);
 const source=await page.request.get(base+'/api/terrain/'+fantasy.source_candidate_id+'/source.png');assert.equal(source.status(),200);fs.writeFileSync(out+'/fantasy-original-download.png',await source.body());
 await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),390);await page.locator('#candidateStatus').screenshot({path:out+'/fantasy-mobile-status.png'});
 const after=await(await page.request.get(base+'/api/generation/status')).json();assert.deepEqual(after,before);assert.deepEqual(errors,[]);const report={result:'PASS',batch:batch.id,layout:batch.frozen.revision,warm_candidate:warm.candidate_id,warm_evaluation:warm.evaluation_id,sampling,navigation,downloads:{layout:layoutDownload,diagnostic,production},fantasy_download_status:blocked.status(),fantasy_production_status:denied.status(),stale_density_status:stale.status(),closed_generation_status:closedConfirm.status(),closed_review_status:closedReview.status(),terminal_resume_unchanged:true,duplicate_start_unchanged:true,known_job_resume_unchanged:true,budget:after,errors};fs.writeFileSync(out+'/browser-report.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));
}finally{await browser.close();}
