import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),links='/root/.cache/ms-playwright/.links';const candidates=fs.readdirSync(links).map(f=>fs.readFileSync(path.join(links,f),'utf8')).filter(p=>fs.existsSync(p+'/package.json'));
const {chromium}=require(process.env.PLAYWRIGHT_CORE||candidates[0]);
const browser=await chromium.launch({executablePath:process.env.CHROMIUM||'/root/.cache/ms-playwright/chromium_headless_shell-1234/chrome-linux/headless_shell',headless:true,args:['--no-sandbox']});
const base=process.env.BASE_URL,out=path.resolve(process.env.EVIDENCE||'evidence/strict-style/browser');fs.mkdirSync(out,{recursive:true});
try{
 const page=await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base);await page.locator('#brief').fill('');await page.getByText('Explizite Formparameter (optional)',{exact:true}).click();await page.locator('#kind').selectOption('urban');await page.locator('#seed').fill('20260922');await page.locator('#generate').click();await page.waitForFunction(()=>window.workbench?.revision);
 const revision=await page.evaluate(()=>window.workbench.revision);
 assert.equal(await page.locator('#styleSpecEditor').count(),1,'versioned editable style specification UI missing');
 await page.locator('#candidateId').fill('f3bdc310f809cf7a6b95015cc16af343e337a192e1865432ac530eb2b02fa96a');await page.locator('#loadCandidate').click();await page.waitForFunction(()=>window.candidateImage?.complete);
 await page.locator('#stylePreset').selectOption('urban-calm-warm');await page.locator('#loadPreset').click();await page.waitForFunction(()=>window.styleSpec?.id);
 const original=await page.locator('#styleSpecEditor').inputValue();const edited=JSON.parse(original);edited.avoid.push('browser-edit verification, no generation');await page.locator('#styleSpecEditor').fill(JSON.stringify(edited,null,2));
 assert(await page.locator('#quoteGeneration').isDisabled());assert.match(await page.locator('#strictReviewStatus').innerText(),/ungültig|unreviewed/);
 await page.locator('#saveStyleSpec').click();await page.waitForFunction(()=>window.styleSpec?.id);const changed=await page.evaluate(()=>window.styleSpec.id);
 await page.locator('#presetName').fill('browser-edit-check');await page.locator('#savePreset').click();await page.waitForFunction(()=>document.querySelector('#styleSpecStatus').textContent.includes('Preset gespeichert'));
 await page.locator('#stylePreset').selectOption('urban-calm-warm');await page.locator('#loadPreset').click();await page.waitForFunction(x=>window.styleSpec?.id&&window.styleSpec.id!==x,changed);
 await page.locator('#quoteGeneration').click();await page.waitForFunction(()=>document.querySelector('#generationReport').textContent.includes('reserve_microusd'));assert(await page.locator('#confirmGeneration').isDisabled());
 await page.locator('#prepareEvaluation').click();await page.waitForFunction(()=>window.currentEvaluation?.status==='reviewed');
 assert.equal(await page.evaluate(()=>window.currentEvaluation.gate.production_approved),false);
 assert.match(await page.locator('#strictReviewStatus').innerText(),/materials: fail/);
 assert(await page.locator('#strictReviewStatus').evaluate(e=>e.clientHeight>=e.scrollHeight),'all criterion verdicts must be visible without clipped review text');
 await page.locator('#styleSpecPanel').screenshot({path:path.join(out,'style-editor.png')});await page.locator('#strictReviewPanel').screenshot({path:path.join(out,'strict-review.png')});
 const wait=page.waitForEvent('download');await page.locator('#candidateDownload').click();const dl=await wait;await dl.saveAs(path.join(out,dl.suggestedFilename()));assert.equal(await dl.failure(),null);assert.match(dl.suggestedFilename(),/diagnostic/);
 await page.locator('#productionExport').click();await page.waitForFunction(()=>document.querySelector('#strictReviewStatus').textContent.includes('Production blocked'));
 await page.locator('#strictReviewPanel').screenshot({path:path.join(out,'production-blocked.png')});assert.equal(await page.evaluate(()=>window.workbench.revision),revision);
 await page.locator('#view').selectOption('candidate');await page.locator('#diagnostics').uncheck();await page.locator('#zoom').click();await page.locator('#scene').screenshot({path:path.join(out,'actual-candidate.png')});
 const state=await page.evaluate(()=>({revision:window.workbench.revision,style:window.styleSpec.id,evaluation:window.currentEvaluation.id}));
 await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),390);await page.locator('#strictReviewPanel').screenshot({path:path.join(out,'review-mobile.png')});
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'browser-report.json'),JSON.stringify({result:'PASS',...state,download:dl.suggestedFilename(),errors},null,2));console.log(JSON.stringify({result:'PASS',out,download:dl.suggestedFilename()}));
}finally{await browser.close();}
