"""Bind actual urban reviews; never promote a secondary pass to production approval."""
from pathlib import Path
import sys,json
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from artifacts import canonical,digest
out=Path('evidence/urban-pilot');r=json.loads((out/'registered-candidate.json').read_bytes());model=json.loads((out/'model-review.json').read_bytes());local=json.loads((out/'registered-local-checks.json').read_bytes())
e=dict(candidate_id=r['id'],layout_revision=r['layout_revision'],source_sha256=r['source_sha256'],guide_sha256=r['guide_sha256'],status='needs_attention',production_approved=False,technical_verdict='pass',semantic_verdict='needs_attention',visual_verdict='secondary_pass_parent_pending',reviewed_terrain_sha256=digest((out/'registered.png').read_bytes()),reviewed_density=1,reviewed_dimensions=[768,408],model_review=model,review_run_id='urban-pilot-01-verified-auth',local_checks=local,style_lineage=json.loads((out/'style-lineage.json').read_bytes()),registration_evidence=json.loads((out/'registration-evidence.json').read_bytes()),browser_verification=json.loads((out/'browser/browser-report.json').read_bytes()),worker_visual_review={'reviewer':'gpt-6-astra subagent; not parent approval','observations':['Genuine distinctly urban gray asphalt carriageway, warm light paving and four protected green pockets; original compact promenade instead of reference intersection.','Fine paving seams and low foliage; no baked cars, people, buildings, trees, bench or kiosk props visible. Technical stick actor remains separate.','Uniform frame fit residual is below 2 canonical pixels per axis. Interior boundaries are not exact: curb gray and green fringes extend outside masks.','All required-route pixels read warm paving; other sidewalk actor footprints touch painted green fringes. Do not change collision to hide this.','Visual style is light and friendly, though reference has denser urban object detail deliberately omitted from ground. Final user/main-session approval remains pending.'],'images':{n:digest((out/n).read_bytes()) for n in ['original.png','registered.png','guide-vs-registered.png','browser/canvas-native.png']}},remaining=['Parent/main-session and user approval pending','Material edge deviations: protected green fringes and gray curb spill; not an automatic all-case material segmentation solution','No production props, character, traffic simulation, engine adapter or public deployment'])
e['id']=digest(canonical(e));target=Path('data/terrain')/r['id']/'review.json'
with target.open('xb') as f:f.write(canonical(e))
(out/'attached-review.json').write_bytes(canonical(e))
print(json.dumps({'review_id':e['id'],'semantic_verdict':e['semantic_verdict'],'visual_verdict':e['visual_verdict']}))
