"""Finish read-only evidence boards, preset readback and compact factual summary."""
import sys,json,io
from pathlib import Path
from decimal import Decimal
import httpx
from PIL import Image,ImageDraw
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from artifacts import canonical,digest
root=Path(__file__).resolve().parents[1];out=root/'evidence/overnight-two-styles';c=httpx.Client(base_url='http://127.0.0.1:59661',timeout=120)
w=json.loads((out/'batch-readback.json').read_bytes());v=json.loads((out/'verification.json').read_bytes());presets=[]
for label,a in zip(('warm','fantasy'),w['styles']):
 name='overnight-'+label;res=c.put('/api/style-presets/'+name,json={'style_spec_id':a['style_spec_id']});res.raise_for_status();p=res.json();allp=c.get('/api/style-presets').json();assert p in allp;presets.append(p)
(out/'presets-readback.json').write_bytes(canonical(presets))
# Same native 3:1 source sampling for comparison, not registration/promotion.
board=Image.new('RGB',(1440,440),'#10191e');draw=ImageDraw.Draw(board)
for i,label in enumerate(('warm','fantasy')):
 im=Image.open(out/label/'source.png').convert('RGB');assert im.size==(2160,1152);im=im.resize((720,384),Image.Resampling.NEAREST);board.paste(im,(i*720,50));draw.text((i*720+10,12),label.upper()+' SOURCE COMPARISON / same 3:1 sampling / NOT GAMEPLAY',fill='white')
board.save(out/'two-styles-source-comparison.png')
visual=dict(reviewer='gpt-6-astra main session, native own vision',external_review_for_this_audit=False,warm=dict(observations=['Cream slab faces and mint ground are distinct, calm and readable. Broad joints remain visible at native720x384.','Crossing paths and four soil patches follow the common guide by eye; no buildings, figures, HUD or copied city geometry.','Visible grass tufts and repeated slabs make a simple isolated technical plaza, not a complete game or reference-scene reproduction.','Small contour roughness and material interpretation remain aesthetic choices; one reviewer pass is not owner acceptance.'],decision='No additional clear visible blocking defect identified at native scale; automatic gate pass retained; user acceptance pending'),fantasy=dict(observations=['Earthier tan cobblestones, olive ground and dark outlines visibly differ from the warm test.','Source remains preserved and unregistered. Residual exceeds frozen bound, not solved by source looking coherent.'],decision='BLOCKED: no gameplay or final-density visual verdict; no forced registration'),images={str(p.relative_to(root)):digest(p.read_bytes()) for p in [out/'warm/final-density.png',out/'warm/reference-vs-source.png',out/'fantasy/reference-vs-source.png',out/'browser/warm-gameplay-native.png',out/'before-after-native.png',out/'registration-replay/overlay-native.png']})
(out/'astra-visual-audit.json').write_bytes(json.dumps(visual,indent=2).encode())
summary=dict(komplett=False,abgearbeitet='Begrenzte Phase abgeschlossen: kostenlose Diagnose verifiziert; beide echten initialen Bilder; warm registriert, reviewed und exportiert; fantasy sicher gestoppt.',blocker=['Fantasy: Registrierung maximal '+str(v['iterations'][1]['registration_max_px'])+'px >2.5px; keine finale Evaluation, kein Gameplay-/Produktions-ZIP.','Altes Urban-Repair bleibt unverändert needs_attention; robustere Diagnose legitimiert keine Gate-Änderung.','Nutzerabnahme warm weiterhin offen.'],echte_neue_images=2,echte_neue_reviews=1,repairs=0,alltime_generation_jobs=v['budget']['attempts'],budget=dict(ceiling_usd='10.00',ceiling_eur='15.00',held_usd=v['budget']['reserved_usd'],new_held_usd=str(Decimal(v['budget']['reserved_usd'])-Decimal(json.loads((out/'budget-before.json').read_bytes())['reserved_usd'])),known_review_usage_alltime_usd=v['known_review_usage_usd'],known_review_usage_new_usd=next(x['reported_cost_usd'] for x in v['review_usage'] if x['id']==w['styles'][0]['evaluation_id']),generation_quotes_alltime_usd=v['budget']['generation_reserved_usd'],unknown_historical_review_hold_usd='0.794112',held_includes_known=True,released_holds=False,paid_controls_closed=True),artifacts=dict(report=str(root/'REPORT-OVERNIGHT-TWO-STYLES.md'),gameplay=str(out/'browser/warm-gameplay-native.png'),before_after=str(out/'before-after-native.png'),style_comparison=str(out/'two-styles-source-comparison.png'),warm_reference_comparison=str(out/'warm/reference-vs-source.png'),fantasy_reference_comparison=str(out/'fantasy/reference-vs-source.png'),production_zip=str(out/'browser/production-candidate.zip'),diagnostic_zip=str(out/'browser/diagnostic-candidate-39825bb50932-d1.zip'),layout_zip=str(out/'browser/layout-92d93124f60c.zip'),verification=str(out/'verification.json')),tests=dict(pytest_passed=117,browser_harnesses=7,downloaded_zips_verified=9),batch_id=w['id'])
(out/'summary.json').write_bytes(json.dumps(summary,indent=2,ensure_ascii=False).encode());print(json.dumps(summary,indent=2,ensure_ascii=False))
