import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {pathToFileURL} from 'node:url';
const require=createRequire(import.meta.url),dir=path.resolve(process.argv[2]);
const links='/root/.cache/ms-playwright/.links',candidates=fs.readdirSync(links).map(f=>fs.readFileSync(path.join(links,f),'utf8')).filter(p=>fs.existsSync(p+'/package.json'));
const {chromium}=require(process.env.PLAYWRIGHT_CORE||candidates[0]);
const browser=await chromium.launch({executablePath:process.env.CHROMIUM||'/root/.cache/ms-playwright/chromium_headless_shell-1234/chrome-linux/headless_shell',headless:true,args:['--no-sandbox']});
try{const page=await browser.newPage({viewport:{width:1450,height:1100}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(pathToFileURL(path.join(dir,'index.html')).href);await page.waitForFunction(()=>window.navigatorReady);
const w=JSON.parse(fs.readFileSync(path.join(dir,'world.json'),'utf8'));
// Independent swept footprint oracle, every cardinal edge including water/cliffs.
function safe(a,b){if(b[0]<0||b[1]<0||b[0]>=w.width||b[1]>=w.height)return false;const half=w.actor_width/2,x0=Math.min(a[0],b[0])+.5-half,x1=Math.max(a[0],b[0])+.5+half,y0=Math.min(a[1],b[1])+.5-half,y1=Math.max(a[1],b[1])+.5+half;if(x0<0||y0<0||x1>w.width||y1>w.height)return false;for(let y=Math.floor(y0);y<Math.ceil(y1);y++)for(let x=Math.floor(x0);x<Math.ceil(x1);x++){if(w.cells[y][x]==='water')return false;for(const [dx,dy]of [[1,0],[0,1]]){let X=x+dx,Y=y+dy;if(X>=Math.ceil(x1)||Y>=Math.ceil(y1))continue;if(w.heights[y][x]!==w.heights[Y][X]&&!w.transitions.some(([p,q])=>(p[0]===x&&p[1]===y&&q[0]===X&&q[1]===Y)||(q[0]===x&&q[1]===y&&p[0]===X&&p[1]===Y)))return false}}return true}
let edges=0;for(let y=0;y<w.height;y++)for(let x=0;x<w.width;x++)for(const [dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]]){const actual=w.graph[`${x},${y}`].some(p=>p[0]===x+dx&&p[1]===y+dy);assert.equal(actual,safe([x,y],[x+dx,y+dy]));edges++}
let moved=0;for(const goal of w.goals){const start=await page.evaluate(()=>window.multilevel.getState().actor);const queue=[start],parents=new Map([[start.join(','),null]]);for(let i=0;i<queue.length;i++)for(const q of w.graph[queue[i].join(',')])if(!parents.has(q.join(','))){parents.set(q.join(','),queue[i]);queue.push(q)}assert(parents.has(goal.join(',')));const route=[];for(let p=goal;p;p=parents.get(p.join(',')))route.push(p);route.reverse();await page.locator('#scene').focus();for(let i=1;i<route.length;i++){const a=route[i-1],b=route[i];const key=b[0]>a[0]?'ArrowRight':b[0]<a[0]?'ArrowLeft':b[1]>a[1]?'ArrowDown':'ArrowUp';await page.keyboard.press(key);await page.waitForFunction(()=>!window.multilevel.getState().moving);assert.deepEqual(await page.evaluate(()=>window.multilevel.getState().actor),b);moved++}}
await page.locator('#scene').screenshot({path:path.join(dir,'browser-native.png')});assert.deepEqual(errors,[]);fs.writeFileSync(path.join(dir,'browser-proof.json'),JSON.stringify({offline:true,edges,moved,goals:w.goals,errors},null,2));console.log(JSON.stringify({offline:true,edges,moved,errors}));
}finally{await browser.close()}
