import fs from 'node:fs';import path from 'node:path';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),base='http://127.0.0.1:48765',out='evidence/hybrid-receipt-continuation';
const rid=JSON.parse(fs.readFileSync(out+'/new-run.json')).id;
const links='/root/.cache/ms-playwright/.links',candidates=fs.readdirSync(links).map(f=>fs.readFileSync(path.join(links,f),'utf8')).filter(p=>fs.existsSync(p+'/package.json'));const {chromium}=require(candidates[0]);
const browser=await chromium.launch({executablePath:'/root/.cache/ms-playwright/chromium_headless_shell-1234/chrome-linux/headless_shell',headless:true,args:['--no-sandbox']});
try{const page=await browser.newPage({viewport:{width:1440,height:1000}});await page.goto(base);await page.evaluate(r=>localStorage.hybridRun=r,rid);await page.reload();await page.waitForFunction(()=>document.querySelector('#status').textContent.length>30);let last='';
for(let i=0;i<180;i++){const r=await(await page.request.get(base+'/api/hybrid-runs/'+rid)).json();if(r.phase!==last){last=r.phase;fs.writeFileSync(out+'/phase-'+r.phase+'.json',JSON.stringify(r,null,2));await page.screenshot({path:out+'/phase-'+r.phase+'.png',fullPage:true});await page.locator('#status').screenshot({path:out+'/status-'+r.phase+'.png'});console.log(JSON.stringify({id:rid,phase:r.phase,calls:r.calls,stop_reason:r.stop_reason}));}if(['succeeded','needs_attention','cancelled'].includes(r.phase)){fs.writeFileSync(out+'/terminal-run.json',JSON.stringify(r,null,2));break;}await page.waitForTimeout(3000);}
await page.setViewportSize({width:1920,height:1280});await page.goto('file://'+path.resolve('data/hybrid/'+rid+'/source-0.png'));await page.evaluate(()=>{document.body.style.margin='0';document.body.style.background='#fff';let i=document.querySelector('img');i.style.cssText='display:block;position:absolute;left:0;top:0;width:1920px;height:1280px;max-width:none;';});await page.locator('img').screenshot({path:out+'/source-native-browser.png'});
}finally{await browser.close()}
